export type ETFHolding = { name: string; weight: number };
export type ETFHoldingsMap = Record<string, ETFHolding[]>;

export const ETF_HOLDINGS: ETFHoldingsMap = {
  // Global All-World
  VWCE: [
    { name: "NVIDIA", weight: 4.22 },
    { name: "Apple", weight: 3.92 },
    { name: "Microsoft", weight: 2.96 },
    { name: "Amazon", weight: 2.05 },
    { name: "Alphabet", weight: 1.85 },
    { name: "Meta", weight: 1.65 },
    { name: "Tesla", weight: 1.20 },
    { name: "Broadcom", weight: 1.10 },
    { name: "TSMC", weight: 0.90 },
    { name: "Eli Lilly", weight: 0.80 },
  ],
  WEBN: [
    { name: "NVIDIA", weight: 4.74 },
    { name: "Apple", weight: 4.12 },
    { name: "Microsoft", weight: 3.00 },
    { name: "Amazon", weight: 2.10 },
    { name: "Alphabet", weight: 1.90 },
    { name: "Broadcom", weight: 1.59 },
    { name: "TSMC", weight: 1.56 },
    { name: "Meta", weight: 1.46 },
    { name: "Tesla", weight: 1.25 },
    { name: "Eli Lilly", weight: 0.95 },
  ],
  // MSCI World (developed only)
  IWDA: [
    { name: "Apple", weight: 4.80 },
    { name: "NVIDIA", weight: 4.50 },
    { name: "Microsoft", weight: 3.50 },
    { name: "Amazon", weight: 2.40 },
    { name: "Meta", weight: 2.10 },
    { name: "Alphabet", weight: 1.90 },
    { name: "Broadcom", weight: 1.60 },
    { name: "Tesla", weight: 1.40 },
    { name: "Eli Lilly", weight: 1.10 },
    { name: "JPMorgan Chase", weight: 1.00 },
  ],
  SWRD: [
    { name: "Apple", weight: 4.80 },
    { name: "NVIDIA", weight: 4.50 },
    { name: "Microsoft", weight: 3.50 },
    { name: "Amazon", weight: 2.40 },
    { name: "Meta", weight: 2.10 },
    { name: "Alphabet", weight: 1.90 },
    { name: "Broadcom", weight: 1.60 },
    { name: "Tesla", weight: 1.40 },
    { name: "Eli Lilly", weight: 1.10 },
    { name: "JPMorgan Chase", weight: 1.00 },
  ],
  // S&P 500
  VUAA: [
    { name: "Apple", weight: 6.50 },
    { name: "NVIDIA", weight: 6.20 },
    { name: "Microsoft", weight: 5.80 },
    { name: "Amazon", weight: 3.80 },
    { name: "Meta", weight: 2.90 },
    { name: "Alphabet", weight: 2.70 },
    { name: "Broadcom", weight: 2.20 },
    { name: "Tesla", weight: 2.00 },
    { name: "Eli Lilly", weight: 1.60 },
    { name: "JPMorgan Chase", weight: 1.50 },
  ],
  CSPX: [
    { name: "Apple", weight: 6.50 },
    { name: "NVIDIA", weight: 6.20 },
    { name: "Microsoft", weight: 5.80 },
    { name: "Amazon", weight: 3.80 },
    { name: "Meta", weight: 2.90 },
    { name: "Alphabet", weight: 2.70 },
    { name: "Broadcom", weight: 2.20 },
    { name: "Tesla", weight: 2.00 },
    { name: "Eli Lilly", weight: 1.60 },
    { name: "JPMorgan Chase", weight: 1.50 },
  ],
  VUSA: [
    { name: "Apple", weight: 6.50 },
    { name: "NVIDIA", weight: 6.20 },
    { name: "Microsoft", weight: 5.80 },
    { name: "Amazon", weight: 3.80 },
    { name: "Meta", weight: 2.90 },
    { name: "Alphabet", weight: 2.70 },
    { name: "Broadcom", weight: 2.20 },
    { name: "Tesla", weight: 2.00 },
    { name: "Eli Lilly", weight: 1.60 },
    { name: "JPMorgan Chase", weight: 1.50 },
  ],
  // Dividend
  VHYL: [
    { name: "HSBC", weight: 2.10 },
    { name: "Samsung", weight: 1.95 },
    { name: "TotalEnergies", weight: 1.80 },
    { name: "Nestle", weight: 1.75 },
    { name: "Roche", weight: 1.70 },
    { name: "Johnson & Johnson", weight: 1.60 },
    { name: "Procter & Gamble", weight: 1.55 },
    { name: "Exxon", weight: 1.50 },
    { name: "AbbVie", weight: 1.40 },
    { name: "Chevron", weight: 1.35 },
  ],
  TDIV: [
    { name: "Roche", weight: 4.83 },
    { name: "HSBC", weight: 4.63 },
    { name: "Pfizer", weight: 4.45 },
    { name: "Verizon", weight: 4.12 },
    { name: "TotalEnergies", weight: 3.85 },
    { name: "Cisco", weight: 3.70 },
    { name: "IBM", weight: 3.45 },
    { name: "Novartis", weight: 3.20 },
    { name: "AstraZeneca", weight: 3.10 },
    { name: "Unilever", weight: 2.90 },
  ],
  // Emerging Markets
  EIMI: [
    { name: "TSMC", weight: 6.80 },
    { name: "Samsung", weight: 3.90 },
    { name: "Tencent", weight: 3.40 },
    { name: "Alibaba", weight: 2.10 },
    { name: "Meituan", weight: 1.20 },
    { name: "Infosys", weight: 1.10 },
    { name: "HDFC Bank", weight: 1.00 },
    { name: "Reliance Industries", weight: 0.95 },
    { name: "SK Hynix", weight: 0.90 },
    { name: "ICICI Bank", weight: 0.85 },
  ],
  VFEM: [
    { name: "TSMC", weight: 7.20 },
    { name: "Samsung", weight: 4.10 },
    { name: "Tencent", weight: 3.60 },
    { name: "Alibaba", weight: 2.20 },
    { name: "Meituan", weight: 1.30 },
    { name: "Infosys", weight: 1.10 },
    { name: "HDFC Bank", weight: 1.05 },
    { name: "Reliance Industries", weight: 1.00 },
    { name: "SK Hynix", weight: 0.95 },
    { name: "ICICI Bank", weight: 0.90 },
  ],
  // Europe
  MEUD: [
    { name: "ASML", weight: 5.20 },
    { name: "Nestle", weight: 4.10 },
    { name: "Novo Nordisk", weight: 3.90 },
    { name: "LVMH", weight: 3.40 },
    { name: "SAP", weight: 3.20 },
    { name: "Roche", weight: 3.00 },
    { name: "AstraZeneca", weight: 2.90 },
    { name: "Novartis", weight: 2.70 },
    { name: "TotalEnergies", weight: 2.50 },
    { name: "Siemens", weight: 2.30 },
  ],
  IEUR: [
    { name: "ASML", weight: 4.80 },
    { name: "Nestle", weight: 3.90 },
    { name: "Novo Nordisk", weight: 3.70 },
    { name: "LVMH", weight: 3.20 },
    { name: "SAP", weight: 3.00 },
    { name: "Roche", weight: 2.80 },
    { name: "AstraZeneca", weight: 2.70 },
    { name: "Novartis", weight: 2.50 },
    { name: "TotalEnergies", weight: 2.30 },
    { name: "Siemens", weight: 2.10 },
  ],
};
